// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: circle.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CirCleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Circle `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CirCleList) Reset() {
	*x = CirCleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_circle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CirCleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CirCleList) ProtoMessage() {}

func (x *CirCleList) ProtoReflect() protoreflect.Message {
	mi := &file_circle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CirCleList.ProtoReflect.Descriptor instead.
func (*CirCleList) Descriptor() ([]byte, []int) {
	return file_circle_proto_rawDescGZIP(), []int{0}
}

func (x *CirCleList) GetItems() []*Circle {
	if x != nil {
		return x.Items
	}
	return nil
}

type Circle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: gorm:"primaryKey;auto_increment;not_null;column:ID"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;auto_increment;not_null;column:ID"`
	// @gotags: gorm:"column:release_time"
	ReleaseTime int64 `protobuf:"varint,2,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty" gorm:"column:release_time"`
	// @gotags: gorm:"column:p_id"
	PId uint32 `protobuf:"varint,3,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty" gorm:"column:p_id"`
	// @gotags: gorm:"column:p_name"
	PName string `protobuf:"bytes,4,opt,name=p_name,json=pName,proto3" json:"p_name,omitempty" gorm:"column:p_name"`
	// @gotags: gorm:"column:content"
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty" gorm:"column:content"`
	// @gotags: gorm:"column:by_time_tall"
	ByTimeTall float32 `protobuf:"fixed32,7,opt,name=by_time_tall,json=byTimeTall,proto3" json:"by_time_tall,omitempty" gorm:"column:by_time_tall"`
	// @gotags: gorm:"column:by_time_weight"
	ByTimeWeight float32 `protobuf:"fixed32,8,opt,name=by_time_weight,json=byTimeWeight,proto3" json:"by_time_weight,omitempty" gorm:"column:by_time_weight"`
	// @gotags: gorm:"column:by_time_age"
	ByTimeAge uint32 `protobuf:"varint,9,opt,name=by_time_age,json=byTimeAge,proto3" json:"by_time_age,omitempty" gorm:"column:by_time_age"`
	// @gotags: gorm:"column:visible"
	Visible bool `protobuf:"varint,10,opt,name=visible,proto3" json:"visible,omitempty" gorm:"column:visible"`
}

func (x *Circle) Reset() {
	*x = Circle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_circle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Circle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circle) ProtoMessage() {}

func (x *Circle) ProtoReflect() protoreflect.Message {
	mi := &file_circle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circle.ProtoReflect.Descriptor instead.
func (*Circle) Descriptor() ([]byte, []int) {
	return file_circle_proto_rawDescGZIP(), []int{1}
}

func (x *Circle) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Circle) GetReleaseTime() int64 {
	if x != nil {
		return x.ReleaseTime
	}
	return 0
}

func (x *Circle) GetPId() uint32 {
	if x != nil {
		return x.PId
	}
	return 0
}

func (x *Circle) GetPName() string {
	if x != nil {
		return x.PName
	}
	return ""
}

func (x *Circle) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Circle) GetByTimeTall() float32 {
	if x != nil {
		return x.ByTimeTall
	}
	return 0
}

func (x *Circle) GetByTimeWeight() float32 {
	if x != nil {
		return x.ByTimeWeight
	}
	return 0
}

func (x *Circle) GetByTimeAge() uint32 {
	if x != nil {
		return x.ByTimeAge
	}
	return 0
}

func (x *Circle) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

var File_circle_proto protoreflect.FileDescriptor

var file_circle_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x61, 0x70, 0x69, 0x73, 0x22, 0x30, 0x0a, 0x0a, 0x43, 0x69, 0x72, 0x43, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x81, 0x02, 0x0a, 0x06, 0x43, 0x69, 0x72, 0x63, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x11, 0x0a, 0x04, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x79, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x62, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x61, 0x6c, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x79,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0c, 0x62, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1e, 0x0a, 0x0b, 0x62, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x61, 0x67, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_circle_proto_rawDescOnce sync.Once
	file_circle_proto_rawDescData = file_circle_proto_rawDesc
)

func file_circle_proto_rawDescGZIP() []byte {
	file_circle_proto_rawDescOnce.Do(func() {
		file_circle_proto_rawDescData = protoimpl.X.CompressGZIP(file_circle_proto_rawDescData)
	})
	return file_circle_proto_rawDescData
}

var file_circle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_circle_proto_goTypes = []interface{}{
	(*CirCleList)(nil), // 0: apis.CirCleList
	(*Circle)(nil),     // 1: apis.Circle
}
var file_circle_proto_depIdxs = []int32{
	1, // 0: apis.CirCleList.items:type_name -> apis.Circle
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_circle_proto_init() }
func file_circle_proto_init() {
	if File_circle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_circle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CirCleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_circle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Circle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_circle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_circle_proto_goTypes,
		DependencyIndexes: file_circle_proto_depIdxs,
		MessageInfos:      file_circle_proto_msgTypes,
	}.Build()
	File_circle_proto = out.File
	file_circle_proto_rawDesc = nil
	file_circle_proto_goTypes = nil
	file_circle_proto_depIdxs = nil
}
